<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE University [
    <!ELEMENT University (Course+)>
    <!ELEMENT Course (CourseName, Professor, Semester, EnrolledStudents, Room, Schedule)>
    <!ELEMENT CourseName (#PCDATA)>
    <!ELEMENT Professor (#PCDATA)>
    <!ELEMENT Semester (#PCDATA)>
    <!ELEMENT EnrolledStudents (#PCDATA)>
    <!ELEMENT Room (#PCDATA)>
    <!ELEMENT Schedule (Date, Time)>
    <!ELEMENT Date (#PCDATA)>
    <!ELEMENT Time (#PCDATA)>
]>

<University>
    <Course>
        <CourseName>Database Systems</CourseName>
        <Professor>Dr. John Smith</Professor>
        <Semester>Fall 2024</Semester>
        <EnrolledStudents>50</EnrolledStudents>
        <Room>101</Room>
        <Schedule>
            <Date>2024-11-15</Date>
            <Time>10:00 AM</Time>
        </Schedule>
    </Course>
    <Course>
        <CourseName>Operating Systems</CourseName>
        <Professor>Dr. Jane Doe</Professor>
        <Semester>Spring 2025</Semester>
        <EnrolledStudents>60</EnrolledStudents>
        <Room>202</Room>
        <Schedule>
            <Date>2025-01-20</Date>
            <Time>02:00 PM</Time>
        </Schedule>
    </Course>
</University>
